name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build with MSBuild
      run: dotnet build --configuration Release --no-restore

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: artifact
        path: ./bin/Release/*.dll

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: artifact
        path: /artifact

    - name: Deploy to GitHub Pages
      run: |
        echo 'Building and deploying to GitHub Pages...'
        mv /artifact/bin/Release/*.dll /var/www/html/
        echo 'Deployed successfully!'
